type Product = {
  id: number;
  category: string;
  name: string;
  price: number;
  image: string;
};

export const products: Product[] = [
  {
    id: 1,
    category: "Men's Dress",
    name: "Men's Formal Suit",
    price: 120,
    image: "src/assets/Products/boy-1.jpg",
  },
  {
    id: 2,
    category: "Women's Dress",
    name: "Evening Gown",
    price: 150,
    image: "src/assets/Products/girl-1.webp",
  },
  {
    id: 3,
    category: "Shoes",
    name: "Running Shoes",
    price: 80,
    image: "src/assets/Products/shoe-1.jpg",
  },
  {
    id: 4,
    category: "Accessories",
    name: "Wallet",
    price: 45,
    image: "src/assets/Products/wallet.jpg",
  },
  {
    id: 5,
    category: "Men's Dress",
    name: "Casual Shirt",
    price: 50,
    image: "src/assets/Products/boy-2.jpg",
  },
  {
    id: 6,
    category: "Women's Dress",
    name: "Summer Dress",
    price: 70,
    image: "src/assets/Products/girl-2.webp",
  },
  {
    id: 7,
    category: "Shoes",
    name: "Formal Leather Shoes",
    price: 100,
    image: "src/assets/Products/Sneakers-2.jpg",
  },
  {
    id: 8,
    category: "Accessories",
    name: "Sunglasses",
    price: 60,
    image: "src/assets/sun-glass.jpg",
  },
  {
    id: 9,
    category: "Men's Dress",
    name: "Jeans",
    price: 65,
    image: "src/assets/Products/boy-3.jpg",
  },
  {
    id: 10,
    category: "Women's Dress",
    name: "Cocktail Dress",
    price: 130,
    image: "src/assets/Products/girl-3.webp",
  },
  {
    id: 11,
    category: "Shoes",
    name: "Sneakers",
    price: 90,
    image: "src/assets/Products/Sneakers.avif",
  },
  {
    id: 12,
    category: "Accessories",
    name: "Watch",
    price: 200,
    image: "src/assets/Products/Watch.jpg",
  },
  {
    id: 13,
    category: "Men's Dress",
    name: "Blazer",
    price: 140,
    image: "src/assets/Products/boy-4.JPG",
  },
  {
    id: 14,
    category: "Women's Dress",
    name: "Maxi Dress",
    price: 110,
    image: "src/assets/Products/girl-4.webp",
  },
  {
    id: 15,
    category: "Shoes",
    name: "Boots",
    price: 120,
    image: "src/assets/Products/Boots.jpg",
  },
  {
    id: 16,
    category: "Accessories",
    name: "Hat",
    price: 30,
    image: "src/assets/Products/Hat.jpg",
  },
  {
    id: 17,
    category: "Men's Dress",
    name: "Trousers",
    price: 55,
    image: "src/assets/Products/boy-5.JPG",
  },
  {
    id: 18,
    category: "Women's Dress",
    name: "Floral Skirt",
    price: 75,
    image: "src/assets/Products/girl-5.webp",
  },
  {
    id: 19,
    category: "Shoes",
    name: "Loafers",
    price: 95,
    image: "src/assets/Products/Loafers.jpg",
  },
  {
    id: 20,
    category: "Accessories",
    name: "Earrings",
    price: 50,
    image: "src/assets/Products/Earrings.jpg",
  },
  {
    id: 21,
    category: "Men's Dress",
    name: "Polo Shirt",
    price: 40,
    image: "src/assets/Products/boy-6.jpg",
  },
  {
    id: 22,
    category: "Women's Dress",
    name: "Casual Blouse",
    price: 60,
    image: "src/assets/Products/girl-6.webp",
  },
  {
    id: 23,
    category: "Shoes",
    name: "High Heels",
    price: 85,
    image: "src/assets/Products/Heels.avif",
  },
  {
    id: 24,
    category: "Accessories",
    name: "Handbag",
    price: 150,
    image: "src/assets/Products/hand-beg.jpg",
  },
  {
    id: 25,
    category: "Men's Dress",
    name: "Winter Jacket",
    price: 180,
    image: "src/assets/Products/boy-6.jpg",
  },
  {
    id: 26,
    category: "Women's Dress",
    name: "Sweater Dress",
    price: 95,
    image: "src/assets/Products/girl-7.webp",
  },
  {
    id: 27,
    category: "Shoes",
    name: "Flip Flops",
    price: 25,
    image: "src/assets/Products/flip.jpg  ",
  },
  {
    id: 28,
    category: "Accessories",
    name: "Belt",
    price: 35,
    image: "src/assets/Products/belt.jpg",
  },
  {
    id: 29,
    category: "Men's Dress",
    name: "Hoodie",
    price: 75,
    image: "src/assets/Products/boy-7.JPG",
  },
  {
    id: 30,
    category: "Women's Dress",
    name: "Denim Jacket",
    price: 90,
    image: "src/assets/Products/girl-8.webp",
  },
  {
    id: 31,
    category: "Shoes",
    name: "Canvas Shoes",
    price: 70,
    image: "src/assets/Products/shoe-4.avif",
  },
  {
    id: 32,
    category: "Accessories",
    name: "Bracelet",
    price: 40,
    image: "src/assets/Products/bracelet.jpg",
  },
  {
    id: 33,
    category: "Men's Dress",
    name: "T-Shirt",
    price: 30,
    image: "src/assets/Products/boy-8.jpg",
  },
  {
    id: 34,
    category: "Women's Dress",
    name: "Leggings",
    price: 50,
    image: "src/assets/Products/girl-9.webp",
  },
  {
    id: 35,
    category: "Shoes",
    name: "Slippers",
    price: 20,
    image: "src/assets/Products/shoe-3.jpg",
  },
  {
    id: 36,
    category: "Accessories",
    name: "Necklace",
    price: 70,
    image: "src/assets/Products/accessories-4.jpg",
  },
  {
    id: 37,
    category: "Men's Dress",
    name: "Denim Shirt",
    price: 60,
    image: "src/assets/Products/boy-8.jpg",
  },
  {
    id: 38,
    category: "Women's Dress",
    name: "Jumpsuit",
    price: 85,
    image: "src/assets/Products/girl-10.webp",
  },
  {
    id: 39,
    category: "Shoes",
    name: "Espadrilles",
    price: 65,
    image: "src/assets/shoe.jpg",
  },
  {
    id: 40,
    category: "Accessories",
    name: "Scarf",
    price: 25,
    image: "src/assets/Products/accessories-3.jpg",
  },
  {
    id: 41,
    category: "Men's Dress",
    name: "Vest",
    price: 35,
    image: "src/assets/Products/boy-9.jpg",
  },
  {
    id: 42,
    category: "Women's Dress",
    name: "Tunic",
    price: 55,
    image: "src/assets/Products/girl-11.webp",
  },
  {
    id: 43,
    category: "Shoes",
    name: "Clogs",
    price: 50,
    image: "src/assets/Products/shoe-2.jpg",
  },
  {
    id: 44,
    category: "Men's Dress",
    name: "Courts",
    price: 35,
    image:
      "src/assets/Products/handsome-fashion-businessman-model-dressed-elegant-blue-suit-posing-street.jpg",
  },
  {
    id: 45,
    category: "Women's Dress",
    name: "kurtis",
    price: 35,
    image:
    "src/assets/Products/young-woman-beautiful-yellow-dress.jpg",
  }
];
